# Generated by Django 5.0 on 2023-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50, null='empty')),
                ('cemail', models.CharField(max_length=100, null='empty')),
                ('cphone', models.CharField(max_length=20, null='empty')),
                ('dob', models.DateField(max_length=20, null='empty')),
                ('cfile', models.FileField(null='empty', upload_to='cand_img')),
                ('cadress', models.CharField(max_length=500, null='empty')),
                ('qualification', models.TextField(null='empty')),
                ('exp', models.CharField(max_length=50, null='empty')),
                ('addskill', models.CharField(max_length=200, null='empty')),
                ('mrg', models.CharField(max_length=50, null='empty')),
                ('job1', models.CharField(max_length=50, null='empty')),
                ('job2', models.CharField(max_length=50, null='empty')),
                ('resume', models.FileField(null='empty', upload_to='cand_resume')),
            ],
        ),
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null='empty')),
                ('femail', models.CharField(max_length=200, null='empty')),
                ('fphone', models.CharField(max_length=200, null='empty')),
                ('fweb', models.CharField(max_length=200, null='empty')),
                ('orgen', models.CharField(max_length=200, null='empty')),
                ('secen', models.CharField(max_length=200, null='empty')),
                ('job_file', models.FileField(null='empty', upload_to='employer_file')),
                ('ename', models.CharField(max_length=200, null='empty')),
                ('desig', models.CharField(max_length=200, null='empty')),
                ('connum', models.CharField(max_length=200, null='empty')),
                ('conemail', models.CharField(max_length=200, null='empty')),
            ],
        ),
    ]
